### ISSUE TITLE
Problem whilst running on XAMPP

### ISSUE THREAD

**Issue by instanceofplayer** [ruany/LiteBans#1]
I attempted to use XAMPP to setup the LiteBans website before I put it on my VPS but for some reason, it keeps trying to use files inside "C:/xampp/apache/[...]" instead of "C:/xampp/htdocs/[...]" even though I've looked all around Google and done everything that says to try and get it to use htdocs instead of apache...

Any help will be appreciated :D

**EDIT:** Should probably put the error that is in Apache's error.log
`script 'C:/xampp/apache/error/tables-not-found.php' not found or unable to stat`

**EDIT 2**: I was finally able to use the panel after I started the server up for the first time but I still want to know how to fix the above issue, should it happen in the future.

**Comment by ruany** [comment]
Issue should be opened on litebans-php, not on the plugin - https://github.com/ruany/litebans-php

I've installed the web interface on a fresh install of XAMPP before and I've never had this issue, though. Error pages worked fine out of the box.

The web interface just does a basic redirect like this: `<script>document.location=error/tables-not-found.php</script>`
The path is generated by your webserver, not by the web interface.

Closing since this isn't an issue with the plugin.
