### ISSUE TITLE
Possible to hook into essential's seen reason?

### ISSUE THREAD

**Issue by mibby** [ruany/LiteBans#23]
Essentials supports showing banned players with a reason upon typing ```/seen <player>``` if players have the permission ```essentials.seen.banreason```. Unfortunately it seems when a player gets banned with litebans, their /seen information no longer updates with a ban message.

Would it be possible to hook into essentials and display a ban reason when looking up when a player was last seen?

**Comment by ruany** [comment]
Not possible, unfortunately.
- As far as I know, Essentials doesn't have any sort of API for this
- Even if it had an API, the command is executed on the main server thread, this would require a database query which has to be done asynchronously.
- Even if both of the previous issues are resolved, if LiteBans is installed under BungeeCord instead of Spigot, there's no way that LiteBans will be able to interact with Essentials directly.

Essentials doesn't support any other banning systems and I don't think any other plugins support this interaction either.

**Comment by mibby** [comment]
Bummer. I suppose I could hand players the ability to check bans with ```/checkban```, however it becomes another process players need to type to find out the status of someone last seen. Not the end of the world.
