### ISSUE TITLE
Separate unban and unbanip.

### ISSUE THREAD

**Issue by mibby** [ruany/LiteBans#26]
Seems a bit odd to allow anyone to unban an IP when normal bans and IP bans require separate permissions?

Also perhaps you may want to keep an IP range banned but allow a specific player to connect again?

**Comment by ruany** [comment]
Normal bans and IP bans are merged together into one UUID+IP ban whenever possible on /ipban, so they are quite closely linked.

It would be an annoyance for existing permissions setups to add another permission specifically for removing IP bans, when /unban already allows you to unban any player that you want to unban, it's not exactly restrictive.

**Comment by mibby** [comment]
Wouldn't it be better to allow IP bans separate in case someone decides to login with alt accounts on the same IP? 

I prefer to keep it restricted to Admins only so normal staff can't ban the ip of the BungeeCord address or all players with a wildcard. It only makes sense to me to not allow the same staff to unban IPs if an IP ban is issued by an Admin for a legitimate serious offense reason.

**Comment by ruany** [comment]
> Wouldn't it be better to allow IP bans separate in case someone decides to login with alt accounts on the same IP?
A UUID+IP ban will prevent that because the IP is banned, I don't see any problem here.

> I prefer to keep it restricted to Admins only so normal staff can't ban the ip of the BungeeCord address or all players with a wildcard. It only makes sense to me to not allow the same staff to unban IPs if an IP ban is issued by an Admin for a legitimate serious offense reason.
Banning the BungeeCord IP should have no effect at all on a properly configured server, because the proxy should be set up to forward player IP addresses instead of reflecting its own address onto all players.

Allowing someone to ban IP addresses (or wildcards) is significant. Allowing someone to unban an IP-banned player is not much more significant than allowing someone to unban a player who is not IP-banned. The same person who could unban IP-banned players issued by an admin can also unban non-IP-banned players issued by an admin.

**Comment by ruany** [comment]
Closing, will only consider this if there's more demand for it.

**Comment by LogGits** [comment]
Tbh this is a great idea. It makes the command more flexible. I would also like to see this come into LiteBans 👍 Great suggestion @mibby. @ruany this is a great plugin, keep up the great work 🙂
