### ISSUE TITLE
"server:" argument improvement

### ISSUE THREAD

**Issue by Blamo27** [ruany/LiteBans#29]
Hello,

Can you make it possible to ban a player from multiple servers at once with the same command, by putting commas ?
Example : /tempban [player] [reason] server:pvp,pvpbox,roleplay

Thanks.

**Comment by ruany** [comment]
I don't plan on implementing this, it would over-complicate the logic for all synchronized commands that support server scopes, since they would have to combine multiple server contexts into effectively the same command handling, which is easier said than done.
All commands are currently designed as: one target (player), one set of queries, one server scope, one final result.
Multiple server scopes would require multiple sets of queries and processing of multiple sets of results with all commands that support them.

It's possible to put multiple servers in a single "group" by giving them all the same server_name, so all punishments in that server group will affect that specific set of servers.

**Comment by Blamo27** [comment]
@ruany So is there a way to tempban a player from multiple servers currently ?

**Comment by ruany** [comment]
> It's possible to put multiple servers in a single "group" by giving them all the same server_name, so all punishments in that server group will affect that specific set of servers.

**Comment by Ferocimo** [comment]
Doing that would mean it would no longer be possible to ban a player from a specific server, since they would be all named the same thing.
